In [266]:
from konlpy.tag import Okt
import pykospacing
import kss
import re
import numpy as np
import pandas as pd

In [267]:
# city 
incheon = pd.read_csv('cluster_data/preprocessed_blog_incheon.csv')
namyangju = pd.read_csv('cluster_data/preprocessed_blog_namyangju.csv')
daegu = pd.read_csv('cluster_data/preprocessed_blog_daegu.csv') 
daejeon = pd.read_csv('cluster_data/preprocessed_blog_daejeon.csv')
yongin = pd.read_csv('cluster_data/preprocessed_blog_yongin.csv')
gwangju = pd.read_csv('cluster_data/preprocessed_blog_gwangju.csv')
ulsan = pd.read_csv('cluster_data/preprocessed_blog_ulsan.csv')
yangyang = pd.read_csv('cluster_data/preprocessed_blog_yangyang.csv')

In [268]:
# city1
mokpo = pd.read_csv('cluster_data/preprocessed_blog_mokpo.csv')
paju = pd.read_csv('cluster_data/preprocessed_blog_paju.csv')
pohang = pd.read_csv('cluster_data/preprocessed_blog_pohang.csv')
seoguepo = pd.read_csv('cluster_data/preprocessed_blog_seguepo.csv')
seoul = pd.read_csv('cluster_data/preprocessed_blog_seoul.csv')
siheung = pd.read_csv('cluster_data/preprocessed_blog_siheung.csv')
jeju = pd.read_csv('cluster_data/preprocessed_blog_jeju.csv')
tongyoung = pd.read_csv('cluster_data/preprocessed_blog_tongyoung.csv')

In [269]:
# city2
gunsan = pd.read_csv('cluster_data/preprocessed_blog_gunsan.csv')
gangreung = pd.read_csv('cluster_data/preprocessed_blog_gangreung.csv')
yeosu = pd.read_csv('cluster_data/preprocessed_blog_yeosu.csv')
hwasung = pd.read_csv('cluster_data/preprocessed_blog_hwasung.csv')
buan = pd.read_csv('cluster_data/preprocessed_blog_buan.csv')
bosung = pd.read_csv('cluster_data/preprocessed_blog_bosung.csv')
changwon = pd.read_csv('cluster_data/preprocessed_blog_changwon.csv')
chungju = pd.read_csv('cluster_data/preprocessed_blog_chungju.csv')
gyungju = pd.read_csv('cluster_data/preprocessed_blog_gyungju.csv')
taean = pd.read_csv('cluster_data/preprocessed_blog_teaan.csv')

In [280]:
city3 = [incheon, 
namyangju,
daegu ,
daejeon ,
yongin ,
gwangju,
ulsan,
yangyang
]

In [271]:
city1 = [mokpo, paju, pohang, seoguepo, seoul, siheung, jeju, tongyoung]
city2 = [gunsan,gangreung,yeosu,hwasung,buan,bosung,changwon,chungju,gyungju,taean]

In [272]:
#결측값 삭제
for c in city:
    c.dropna(inplace=True)
    c.reset_index(inplace=True,drop=True)

In [273]:
#결측값 삭제
for c in city1:
    c.dropna(inplace=True)
    c.reset_index(inplace=True,drop=True)

In [274]:
#결측값 삭제
for c in city2:
    c.dropna(inplace=True)
    c.reset_index(inplace=True,drop=True)

In [23]:
for j in range(8):
    a = []
    
    for i in word_fre_list[j].keys():
        if i in notuse:
            a.append(i)

    for i in a:
        del word_fre_list[j][i]

NameError: name 'word_fre_list' is not defined

In [85]:
from itertools import islice

for i in range(8):
    word_fre_list[i] = dict(islice(word_fre_list[i].items(), 50))

In [86]:
word_fre_list

[{'소래포구': 7346,
  '바다': 7019,
  '해수욕장': 6721,
  '파크': 6715,
  '센트럴': 5480,
  '어시장': 4892,
  '조개': 4831,
  '카페': 3865,
  '구이': 3417,
  '호텔': 2719,
  '새우': 2693,
  '공원': 2098,
  '보트': 2092,
  '칼국수': 1932,
  '식당': 1658,
  '해변': 1630,
  '횟집': 1616,
  '해산물': 1598,
  '바위': 1597,
  '튀김': 1364,
  '해물': 1285,
  '광역시': 1275,
  '대하': 1264,
  '저녁': 1252,
  '꽃게': 1243,
  '음식': 1200,
  '커피': 1148,
  '남동구': 1144,
  '고기': 1108,
  '산책': 1102,
  '오션': 1094,
  '여름': 1076,
  '라면': 1074,
  '갈매기': 1047,
  '놀이': 1041,
  '데이트': 1019,
  '풍경': 1008,
  '물회': 982,
  '가리비': 966,
  '광어': 927,
  '시장': 923,
  '양념': 920,
  '일몰': 907,
  '서비스': 860,
  '차이나타운': 858,
  '소금': 858,
  '미도': 822,
  '왕산': 820,
  '소래': 814,
  '기본': 813},
 {'정원': 8034,
  '물의': 7416,
  '정약용': 5196,
  '다산': 3824,
  '유적지': 2970,
  '공원': 2313,
  '양귀비': 2061,
  '산책': 1517,
  '자전거': 1508,
  '생태': 1363,
  '풍경': 1339,
  '실학': 1206,
  '카페': 1114,
  '나들이': 1095,
  '코스모스': 1092,
  '박물관': 1051,
  '생가': 985,
  '가을': 965,
  '여유당': 937,
  '강변': 935,
  '근교': 895,
  '한강로': 808,
  '수종사': 778,
  '드라이브': 760,
  '자연': 663,
  '두물머리': 629,
  '하늘': 627,
  '산책로': 606,
  '다산로': 580,
  '기념관': 545,
  '데이트': 539,
  '체험': 479,
  '황화': 478,
  '초록': 475,
  '운길산역': 471,
  '힐링': 464,
  '운길산': 458,
  '한강': 453,
  '폭포': 447,
  '여름': 444,
  '전시': 444,
  '장어': 443,
  '화관': 437,
  '미나리': 416,
  '겨울': 392,
  '피아노': 387,
  '그늘': 384,
  '꽃밭': 379,
  '걷기': 372,
  '연꽃': 369},
 {'팔공산': 9181,
  '케이블카': 8800,
  '이월드': 8043,
  '서문시장': 7501,
  '수목원': 7204,
  '엑스코': 6484,
  '카페': 5603,
  '월드': 4759,
  '커피': 3456,
  '식당': 3172,
  '벚꽃': 3016,
  '음식': 3008,
  '고기': 2879,
  '호텔': 2876,
  '인터': 2434,
  '체험': 2387,
  '단풍': 2288,
  '타워': 2236,
  '시장': 2097,
  '공원': 1942,
  '축제': 1924,
  '칼국수': 1849,
  '김밥': 1795,
  '가을': 1780,
  '놀이': 1733,
  '갈비': 1719,
  '여름': 1674,
  '데이트': 1613,
  '박람회': 1549,
  '피자': 1537,
  '저녁': 1485,
  '놀이기구': 1411,
  '풍경': 1356,
  '행사': 1312,
  '산책': 1299,
  '샐러드': 1236,
  '떡볶이': 1207,
  '지구': 1197,
  '이용권': 1194,
  '전시': 1184,
  '막창': 1160,
  '양념': 1145,
  '돈까스': 1131,
  '소원': 1129,
  '메밀': 1127,
  '자유': 1124,
  '튀김': 1118,
  '파스타': 1115,
  '기본': 1115,
  '이벤트': 1107},
 {'엑스포': 12257,
  '아쿠아리움': 10341,
  '오월드': 8037,
  '장태산': 6728,
  '공원': 5582,
  '한밭수목원': 5381,
  '자연휴양림': 4741,
  '체험': 4636,
  '신세계': 4364,
  '공연': 3866,
  '과학': 3543,
  '물고기': 3497,
  '수목원': 3008,
  '장미': 2466,
  '백화점': 2463,
  '음악분수': 2399,
  '사파리': 2347,
  '한빛탑': 2146,
  '수조': 2086,
  '카페': 1993,
  '온천': 1938,
  '동물': 1891,
  '광장': 1886,
  '가을': 1845,
  '축제': 1832,
  '물놀이': 1813,
  '휴양림': 1752,
  '식물원': 1715,
  '전망대': 1695,
  '동원': 1682,
  '산책': 1666,
  '버드': 1576,
  '아기': 1526,
  '동물원': 1522,
  '풍경': 1491,
  '놀이': 1474,
  '분수': 1468,
  '자연': 1385,
  '플라워': 1384,
  '여름': 1359,
  '전시': 1346,
  '놀이기구': 1343,
  '유니버스': 1332,
  '데이트': 1284,
  '나들이': 1258,
  '호텔': 1186,
  '스카이': 1185,
  '메인': 1106,
  '힐스테이트': 1105,
  '서원': 1105},
 {'에버랜드': 14353,
  '민속촌': 12263,
  '베이': 10129,
  '캐리비안': 9158,
  '백남준': 7190,
  '체험': 5177,
  '사이드': 4803,
  '레이크': 4701,
  '아트': 4365,
  '센터': 4106,
  '공연': 4022,
  '자연휴양림': 3876,
  '골프': 3697,
  '골프장': 3509,
  '바오': 3077,
  '전시': 3038,
  '놀이': 2961,
  '여름': 2901,
  '놀이기구': 2241,
  '카페': 2075,
  '판다': 1811,
  '클럽': 1799,
  '물놀이': 1795,
  '월드': 1656,
  '그린': 1585,
  '호텔': 1501,
  '실내': 1495,
  '파도': 1419,
  '컨트리클럽': 1400,
  '저녁': 1366,
  '자연': 1351,
  '밸리': 1340,
  '사파리': 1297,
  '퍼레이드': 1284,
  '스톰': 1260,
  '카드': 1253,
  '정문': 1200,
  '예술': 1183,
  '파도풀': 1175,
  '식당': 1172,
  '이벤트': 1168,
  '아기': 1164,
  '튜브': 1157,
  '데크': 1148,
  '서기': 1140,
  '음식': 1126,
  '한복': 1116,
  '나들이': 1068,
  '캠핑': 1051,
  '법인': 1046},
 {'기아': 5575,
  '필드': 4292,
  '챔피언스': 4274,
  '응원': 2106,
  '송정역': 2073,
  '야구': 2043,
  '시장': 2022,
  '타이거즈': 1723,
  '야구장': 1692,
  '광역시': 1430,
  '경기장': 1212,
  '직관': 1200,
  '국밥': 1129,
  '치킨': 790,
  '맥주': 786,
  '먹거리': 630,
  '떡볶이': 613,
  '음식': 498,
  '국수': 488,
  '계란': 472,
  '롯데': 433,
  '카페': 414,
  '구장': 389,
  '투수': 388,
  '영명': 378,
  '응원가': 378,
  '호두과자': 377,
  '양갱': 342,
  '식빵': 339,
  '크림': 339,
  '삼성': 332,
  '떡갈비': 322,
  '두산': 304,
  '추억': 301,
  '초코파이': 301,
  '카드': 296,
  '튀김': 290,
  '저녁': 279,
  '전통': 274,
  '선물': 272,
  '스카이': 265,
  '스토어': 263,
  '전라도': 262,
  '고기': 260,
  '완전': 254,
  '라면': 254,
  '족발': 254,
  '순대': 252,
  '박스': 249,
  '양현종': 243},
 {'고래': 19302,
  '대왕암': 13331,
  '해수욕장': 12659,
  '공원': 10979,
  '바다': 8084,
  '체험': 7679,
  '간절곶': 7106,
  '생태': 7095,
  '장생포': 6964,
  '등대': 5871,
  '돌고래': 5693,
  '광역시': 5108,
  '카페': 4275,
  '박물관': 4125,
  '수족관': 2497,
  '바위': 2134,
  '풍경': 1951,
  '커피': 1796,
  '해변': 1751,
  '여름': 1728,
  '산책': 1643,
  '고기': 1551,
  '축제': 1490,
  '모노레일': 1398,
  '일출': 1378,
  '파도': 1297,
  '소망': 1246,
  '물고기': 1207,
  '산책로': 1181,
  '서핑': 1180,
  '바닷가': 1178,
  '식당': 1164,
  '야경': 1100,
  '아기': 1050,
  '물놀이': 1033,
  '조개': 989,
  '저녁': 988,
  '모래': 950,
  '전망대': 926,
  '수국': 884,
  '해안': 877,
  '놀이': 876,
  '조명': 867,
  '캠핑장': 866,
  '하늘': 847,
  '해양': 809,
  '데이트': 784,
  '가까이': 763,
  '호텔': 756,
  '태화강': 723},
 {'물회': 16211,
  '청초': 9802,
  '해수욕장': 9353,
  '체스터': 8276,
  '톤스': 7937,
  '설악산': 7731,
  '호텔': 7004,
  '바다': 6027,
  '수영장': 4529,
  '수산시장': 4381,
  '닭강정': 4246,
  '카페': 3793,
  '시장': 3482,
  '국립공원': 3437,
  '중앙시장': 3419,
  '관람차': 2834,
  '케이블카': 2551,
  '오징어': 2450,
  '바위': 2405,
  '음식': 2221,
  '해변': 2171,
  '대게': 2043,
  '튀김': 1995,
  '저녁': 1937,
  '여름': 1888,
  '본점': 1884,
  '먹거리': 1701,
  '순대': 1680,
  '엑스포로': 1678,
  '오징어순대': 1601,
  '식당': 1587,
  '전복': 1539,
  '커피': 1491,
  '해전': 1461,
  '풍경': 1405,
  '설악': 1288,
  '비빔밥': 1248,
  '성게': 1161,
  '센터': 1160,
  '폭포': 1159,
  '공원': 1127,
  '새우': 1117,
  '요리': 1110,
  '호수': 1088,
  '리조트': 1084,
  '육수': 1068,
  '침대': 1034,
  '등산': 1032,
  '오션': 1030,
  '웨이': 1025}]

In [ ]:
# 단어 정규화를 통해 정확도 향상
# 띄어쓰기로 인해 분리된 토큰을 하나로 합침.

In [275]:
def text_normalization(city):
    for i in range(len(city)):
        texts = city['preprocessed_content'][i]

        #단어 정규화
        texts = texts.replace('고 군산 군도','고군 산군도').replace('고군산군도','고군산군도')
        texts = texts.replace('군산도','고군산군도')
        texts = texts.replace('설악 산','설악산')
        texts = texts.replace('이 월드','이월드')
        texts = texts.replace('바닷가','바다').replace('해수욕장','해안')
        texts = texts.replace('굴','동굴')
        texts = texts.replace('물의 정원','물의정원')
        texts = texts.replace('다산 정약용','정약용')
        texts = texts.replace('센트럴 파크','센트럴파크')
        texts = texts.replace('선 유도','선유 도').replace('선유도','선유도')
        texts = texts.replace('무 녀도','무녀 도').replace('무녀도','무녀도')
        texts = texts.replace('비 응도','비응도')
        texts = texts.replace('비 응항','비응 항').replace('비응항','비응항')
        texts = texts.replace('변산 반도','변산반도')
        texts = texts.replace('은파 호수','은파호수')
        texts = texts.replace('스카이 라인', '스카이라인')
        texts = texts.replace('은파 호수 공원','은파호수 공원').replace('은파호수공원','은파호수공원')
        texts = texts.replace('문화 유산','문화유산')
        texts = texts.replace('선셋','일몰')
        texts = texts.replace('공동묘지','묘지')
        texts = texts.replace('반려견','반려동물').replace('반려 견','반려동물')
        texts = texts.replace('애완 견', '반려동물').replace('애완견','반려동물')
        texts = texts.replace('애완동물','반려동물').replace('애완 동물','반려동물')
        texts = texts.replace('애기', '아기')
        texts = texts.replace('초딩', '초등학생')
        texts = texts.replace('칭구', '친구')
        texts = texts.replace('미륵 전', '미륵전')
        texts = texts.replace('채석 강', '채석강')
        texts = texts.replace('해식 동굴', '해식동굴')
        texts = texts.replace('관음 정사', '관음정사')
        texts = texts.replace('관음 봉', '관음봉')
        texts = texts.replace('워터 파크', '워터파크')
        texts = texts.replace('금 산사', '금산 사').replace('금산사','금산사')
        texts = texts.replace('변산 반도','변산반도')
        texts = texts.replace('롯데 월드', '롯데월드')
        texts = texts.replace('농경 문화 박물관', '농경문화 박물관').replace('농경문화박물관','농경문화박물관')
        texts = texts.replace('혜덕 왕사 탑비', '혜덕왕사 탑비').replace('혜덕왕사탑비','혜덕왕사탑비')
        texts = texts.replace('인터 불고','인터불고')
        texts = texts.replace('버드 랜드','버드랜드')
        texts = texts.replace('캐리비안 베이','캐리비안베이')
        texts = texts.replace('레이크 사이드','레이크사이드')
        texts = texts.replace('아트 홀','아트홀')
        texts = texts.replace('아트 센터','아트센터')
        texts = texts.replace('용인 월드','수영장')
        texts = texts.replace('챔피언스 필드','챔피언스필드')
        texts = texts.replace('야 구장','야구장')
        texts = texts.replace('소망 우체통','소망우체통')
        texts = texts.replace('청초 호','청초호')
        texts = texts.replace('체스터 톤스','체스터톤스')
        texts = texts.replace('엑스포로','엑스포')
        texts = texts.replace('엑스포 타워','엑스포타워')
        texts = texts.replace('근대 역사관','근대역사관')
        texts = texts.replace('자연사 박물관','자연사박물관')
        texts = texts.replace('마장 호수','마장호수')
        texts = texts.replace('델루','호텔델루나촬영지')
        texts = texts.replace('평화 랜드','평화랜드')
        texts = texts.replace('평화 누리공원','평화누리공원')
        texts = texts.replace('평화누리 공원','평화누리공원')
        texts = texts.replace('벽초지 수목원','벽초지수목원')
        texts = texts.replace('헤이리 예술마을','헤이리예술마을')
        texts = texts.replace(' 폭포','폭포')
        texts = texts.replace(' 일출봉','일출봉')
        texts = texts.replace('드르','카페')
        texts = texts.replace('라울','전시회')
        texts = texts.replace('스타 필드','스타필드')
        texts = texts.replace('갯골 생태 공원','갯골생태공원')
        texts = texts.replace('갯골 생태공원','갯골생태공원')
        texts = texts.replace('갯골생태 공원','갯골생태공원')
        texts = texts.replace('웨이브 파크','웨이브파크')
        texts = texts.replace('스카이 큐브', '스카이큐브')
        texts = texts.replace('순천만 국가정원', '순천만국가정원')
        texts = texts.replace('스카이라인 루지', '스카이라인루지')
        texts = texts.replace('스카이 라인 루지', '스카이라인루지')
        texts = texts.replace('이순신 공원', '이순신공원')
        texts = texts.replace('경주 월드','경주월드')
        texts = texts.replace('핑크 뮬리','핑크뮬리')
        texts = texts.replace('고 군산 군도','고군 산군도').replace('고군산군도','고군산군도')
        texts = texts.replace('군산도','고군산군도')
        texts = texts.replace('비 응도','비응도')
        texts = texts.replace('비 응항','비응 항').replace('비응항','비응항')
        texts = texts.replace('적벽 노을 길','적벽 강').replace('적벽노을길','적벽강')
        texts = texts.replace('변산 반도','변산반도')
        texts = texts.replace('강문 해변','강문해변')
        texts = texts.replace('아르떼 뮤지엄','아르떼 뮤 지엄').replace('아르떼뮤지엄','아르떼뮤지엄')
        texts = texts.replace('아르떼','아르떼뮤지엄')
        texts = texts.replace('초당 순두부','초당순두부')
        texts = texts.replace('허난 설헌','허난설헌')
        texts = texts.replace('허난설헌','허난설헌기념관')
        texts = texts.replace('하멜 등대','하멜등대')
        texts = texts.replace('하멜 동상','하멜동상')
        texts = texts.replace('양념 게장','양념게장')
        texts = texts.replace('여 수당','여수당')
        texts = texts.replace('궁평 항','궁평항')
        texts = texts.replace('국립 공원','국립공원')
        texts = texts.replace('백합 정식','백합정식')
        texts = texts.replace('놀이 기구','놀이기구')
        texts = texts.replace('로봇 랜드','로봇랜드')
        texts = texts.replace('용지 공원','용지공원')
        texts = texts.replace('용지 못','용지못')
        texts = texts.replace('워터 파크','워터파크')
        texts = texts.replace('마산 로봇 랜드','로봇랜드')
        texts = texts.replace('창원 과학 체험 관','창원과학체험관')
        texts = texts.replace('창원 과학 체험관','창원과학체험관')
        texts = texts.replace('과학 체험','창원과학체험관')
        texts = texts.replace('무빙 보트','무빙보트')
        texts = texts.replace('청주 랜드','청주랜드')
        texts = texts.replace('청주 동물원','동물원')
        texts = texts.replace('원숭이','사자').replace('동물','동물')
        texts = texts.replace('호랑이','동물')
        texts = texts.replace('토끼','동물')
        texts = texts.replace('대청 호','대청호')
        texts = texts.replace('대청 댐','대청댐')
        texts = texts.replace('대 청호','대청호')
        texts = texts.replace('대 청댐','대청댐')
        texts = texts.replace('청남대 본관','청남대')
        texts = texts.replace('석 굴암','석굴암')
        texts = texts.replace('국립 경주 박물관','박물관')
        texts = texts.replace('국립 박물관','박물관')
        texts = texts.replace('캘리포니아 비치','경주월드')
        texts = texts.replace('경주 캘리포니아 비치','경주월드')
        texts = texts.replace('천마총 금관','천마총금관')
        texts = texts.replace('동궁 월지','동궁월지')
        texts = texts.replace('황리 단길','황리단길')
        texts = texts.replace('드라켄','놀이기구')
        texts = texts.replace('신라 호텔','신라호텔')
        texts = texts.replace('월 정교','월정교')
        texts = texts.replace('경주 월 정교','월정교')
        texts = texts.replace('강문 해변','강문해변')

In [276]:
for i in city:
    text_normalization(i)

In [277]:
for i in city1:
    text_normalization(i)

In [278]:
for i in city2:
    text_normalization(i)

In [279]:
# 정규화 및 1차 전처리 후에도, 각 크롤링 데이터마다 분석에 불필요한 단어들이 다수 존재했음.
# 명사들을 빈도 순으로 나열한 후, 불필요한 단어들을 추가적으로 제거하는 작업 진행.

notuse = ['단체', '영천', '락커', '만석', '함안시', '네이버', '더욱', '강원도', '보령시', '삼척', '영양시', '확인', 
          '강진', '출구', '안성', '저녁', '좌석', '경험', '머리', '골목', '광주시', '울주군', '숲길', '동문', '추천',
          '원주시', '회천면', '고속도로', '간다', '종류', '먹이', '영동시', '촬영', '보고', '식물', '결제', '우암',
          '신안시', '명동', '토닉', '북구', '방죽', '용인', '도착', '경암동', '설치', '새만금', '방콕', '보지', '근처',
          '매표소', '구입', '곡성시', '예전', '천안시', '밀양시', '제일', '부안', '성산읍', '휴가', '경산시', '생각',
          '이제', '모양', '서서', '국민', '충청남도', '소니', '성남시', '코로나', '스테이션', '금산', '고민', '어른',
          '평일', '대로', '충주', '의정부시', '개함', '무주시', '창녕', '승용차', '구매', '고택', '종합', '생기', '음성시',
          '다람쥐', '공주', '무주', '세종시', '경기도', '철원시', '곡성', '아가', '시즌', '고흥', '상당구', '전북', '이후',
          '강원시', '춘천', '개구', '작년', '금산시', '청송', '한국', '천하', '왕리', '장성시', '기북면', '영광시', '정보', 
          '강릉', '소개', '사람', '보호', '구성', '유성', '파주', '출처', '진천시', '창원시', '제대로', '지수', '지금',
          '소사', '선녀', '동구', '청양시', '포리', '처음', '통영', '남구', '일대', '담양', '군산', '부산', '제주시',
          '영광', '현대', '모험', '입장권', '가게', '의정부', '위해', '보기', '최근', '청양', '청주시', '이나', '스페이스',
          '안덕면', '단양', '알다', '아산', '나주', '근교', '서생면', '매력', '시작', '크리스탈', '아우', '입다', '규모',
          '처럼', '국내', '이기', '고창시', '문경시', '때문', '화순시', '고령', '증평', '산청', '시설', '하동', '워낙',
          '죽교동', '왕복', '철원', '마르다', '방법', '사용', '부산시', '성인', '안양시', '소스', '구룡포읍', '계속',
          '청송시', '분홍', '투어', '평창시', '옥천시', '실제', '경기시', '익산시', '여러', '아벨', '시야', '변산', 
          '안전', '영덕', '경주', '후기', '국제', '객실', '김해시', '대구시', '장수시', '맞이', '아들', '덕동', '김천시',
          '구리', '양산', '공사', '발견', '경주시', '지엄', '가족', '경상남도', '어린이', '건물', '대충', '시대', '인분',
          '임실시', '개항', '주식회사', '조류', '보은', '추가', '길이', '조성', '장수', '사랑', '거창', '순천', '소녀', 
          '창녕시', '경기', '궁평리', '화장실', '주차장', '우체통', '별로', '소요', '보성군', '음료', '청주', '예약',
          '영주', '양구', '아빠', '대기', '전두환', '홍성', '수도', '이용권', '화천', '고흥시', '최고', '삼척시', '도시',
          '소리', '나주시', '하니', '부여시', '탄현면', '강릉시', '선생', '현재', '청원구', '특별', '만천하', '고령시',
          '다시', '기도', '아바이', '함양', '광탄면', '구리시', '서산시', '격포', '장소', '전남시', '남아', '정선시',
          '서문', '분위기', '일정', '인천시', '단양시', '선수', '성주', '지하', '인증', '문집', '계룡시', '감상',
          '우리나라', '산청시', '개월', '회관', '방문', '경남시', '입장료', '공작', '인천', '주소', '순간', '충주시',
          '남원시', '안동시', '서천', '사이', '무안', '금강로', '대구광역시', '통해', '인제', '제천시', '영상', '진주', 
          '맛집', '미래', '중앙', '가지', '기분', '위치', '회원', '웨이', '수성구', '금방', '남해', '관광지', '유니폼',
          '대표', '돌산읍', '광진구', '햇살', '담양시', '그림', '김치', '아주', '상주시', '성남', '보은시', '광산구',
          '파다', '할인', '서귀포시', '서리', '울산', '노래', '완도시', '성주시', '홍성시', '문화', '상당', '등기', '관람',
          '오픈', '돗자리', '커플', '구미', '특별자치도', '예산시', '제천', '반찬', '날씨', '벤치', '진도', '인천광역시',
          '광양', '진해구', '계룡', '거제시', '진안', '경복궁역', '관련', '인테리어', '초등학생', '여서', '순창시', 
          '보성시', '파란', '안산', '광양시', '주말', '가능', '소나무', '충청북도', '티뮤', '개인', '정말', '지다', 
          '남해시', '금성로', '그대로', '태백시', '정선', '유아', '라이드', '선도', '안성시', '전라남도', '카드', '창원',
          '키즈', '영업', '그냥', '불가', '지도', '거제', '용담', '역시', '내부', '계정', '사천', '일본', '서구', '보이', 
          '경산', '광주광역시', '이전', '먼저', '프로그램', '준비', '울진', '고성', '인지', '일제', '만들기', '약용', 
          '입구', '포장', '음성', '평창', '마당', '경우', '양주', '관광객', '여기', '아침', '명소', '라서', '만큼', 
          '김제시', '청도시', '설명', '남원', '리뷰', '멀리', '사실', '작가', '서울', '원래', '미호', '돼지', '노벨', 
          '열대', '검색', '시흥시', '매일', '관람객', '오이도', '입장', '지점', '의미', '지진', '서산', '계단', '원정',
          '조각', '장항', '공간', '사장', '포항시', '평택', '숙소', '북한', '완주시', '임실', '시흥', '개장', '대전광역시',
          '리다', '자꾸', '영주시', '식사', '진행', '여수', '기장', '고하도', '본인', '보성', '김천', '경남', '부산여행',
          '손님', '춘천시', '장흥', '문의면', '오늘', '가득', '헬멧', '제주', '리해', '연수구', '세종특별시', '일반',
          '마감', '수산', '이니스프리', '마산', '캐빈', '세트', '괴산시', '만난', '월요일', '가격', '옥천', '증평시',
          '경북', '서울시', '마이', '포스팅', '친구', '합천', '임진각로', '강진시', '하루', '울산시', '처인구', '대전',
          '문경', '동쪽', '충북', '시내', '고양시', '순천시', '거창시', '자산', '참고', '예정', '재생', '순창', '이동', 
          '함양시', '다스', '의성시', '야간', '달서구', '점심', '예매', '반기', '해상', '의성', '탑승', '진짜', '연어',
          '유배', '공기', '나무', '전주시', '영암시', '면제', '아산시', '바람', '김포', '레드', '트랙', '수원시', '강원',
          '늠길', '익산', '김해', '청소년', '높이', '대한', '마을', '군산시', '메뉴', '휴무', '곳곳', '마지막', '양구시',
          '일본인', '살짝', '만날', '양주시', '재미', '서신면', '타고', '관리', '모형', '계획', '기념', '파주시', '양산시',
          '광주', '수암', '주차', '나이트', '유리', '먹기', '목포시', '바닥', '포곡읍', '제법', '이름', '부천', '보령',
          '부분', '일산', '강습', '이용', '운영', '토요일', '승리', '일상', '외야', '여수시', '변산면', '움직', '애기',
          '김제', '느낌', '당시', '서울특별시', '구산면', '완주', '혼례', '방향', '목포역진서면', '사천시', '진주시',
          '천안', '장흥시', '문산읍', '평택시', '부여', '괴산', '속초', '동해', '대전시', '전체', '스마트', '신발', '근대',
          '치즈', '예산', '정읍', '당진시', '나중', '영덕시', '부담', '대회', '거기', '시민', '피어', '김포시', '경매',
          '전북시', '작품', '화순', '정읍시', '인제시', '국물', '더위', '가장', '고성시', '라이딩', '유성구', '함평시',
          '미시', '합천시', '하동시', '여행', '영종도', '화성시', '아파트', '화성', '함평', '엄마', '만원', '자리', '송정',
          '보호자', '관광', '일산동', '성산구', '무료', '태백', '오산시', '모습', '볼거리', '동포', '찍기', '암문', '헤어',
          '논산', '카인', '포토', '부산광역시', '진천', '안동', '전경', '아무', '발권', '안내', '월미도', '서로', '가면',
          '게임', '수원', '태안시', '군위시', '보성읍', '이야기', '목포', '야외', '당진', '전국', '진안시', '미리', '완도',
          '통영시', '고양', '청도', '군위', '사진', '메이크업', '도로', '구미시', '요금', '기억', '제주도', '포항', '메뉴판',
          '배곧', '경사', '남양주시', '영동', '무안시', '계시', '용인시', '밀양', '건너', '속초시', '요기', '구례시', 
          '아래', '정도', '코스', '대여', '마련', '신안', '특징', '선택', '지정', '세계', '정상', '구경', '남양주', '지로',
          '도박', '오후', '호반', '문의', '버스', '홍천', '홍천시', '티켓', '공주시', '사강', '거리', '지역', '습관',
          '제한', '영화', '상주', '가성', '판매', '트릭', '물이', '해남시', '구례', '도심', '태안', '논산시', '오전',
          '장성', '원주', '서천시', '중간', '충북시', '충남', '진도시', '경북시', '화천시', '영암', '오시', '추석', '주변',
          '조안면', '직접', '주문', '금지', '뭔가', '벌써', '기흥구', '영산로', '구간', '장료', '천원', '다리', '여행지',
          '오산', '생활', '부안군', '출발', '고창', '의자', '노량진', '전라북도', '아기', '요즘', '경상북도', '충남시',
          '부천시', '해남', '중구', '블록', '정기', '함안', '테마', '부안시', '대해', '전남', '송도', '소래역', '대구', 
          '기간', '영양', '이지', '마다', '영천시', '안산시', '전주', '체크', '홈런', '설리', '양평', '수성', '테이블', 
          '상생', '세종', '디피', '매장', '초록', '접기', '마음', '울산광역시', '관찰', '동해시', '안양', '열차']

In [281]:
len(city1)

8

In [317]:
pos_text_list_1=["","","","","","","",""]

In [318]:
for i in range(len(city1)):
    for _, row in city1[i].iterrows():
        pos_text_list_1[i] += row['preprocessed_content']

In [319]:
len(city2)

10

In [320]:
pos_text_list_2=["","","","","","","","",'','']

In [321]:
for i in range(len(city2)):
    for _, row in city2[i].iterrows():
        pos_text_list_2[i] += row['preprocessed_content']

In [322]:
len(city3)

8

In [323]:
pos_text_list_3=["","","","","","","",""]

In [324]:
for i in range(len(city3)):
    for _, row in city3[i].iterrows():
        pos_text_list_3[i] += row['preprocessed_content']

# 명사 추출 후 빈도 수 확인

In [325]:
okt = Okt()

In [370]:
myList=[]
myList_filter=[]

In [371]:
for i in range(8):
    myList.append(okt.pos(pos_text_list_3[i], norm=True, stem=True)) # 모든 형태소 추출
    myList_filter.append([x for x, y in myList[i] if y in ['Noun']]) # 추출된 값 중 명사만 추출

In [372]:
nouns_list= []

In [373]:
for i in range(8):
    nouns_list.append(' '.join(myList_filter[i]))

In [374]:
word_frequencies_list=[]

In [375]:
from collections import Counter

def count_word_frequencies(corpus):
    # 단어 빈도수를 저장할 Counter 객체 생성
    word_counter = Counter()

    # 말뭉치에서 각 단어 추출하여 빈도수 계산
    words = corpus.split()
    words= [x for x in words if x not in notuse]
    word_counter.update(words)

    # 단어 빈도수를 딕셔너리로 변환
    word_frequency_dict = {word: frequency for word, frequency in word_counter.items()}

    return word_frequency_dict


for i in range(8):
    # 말뭉치 데이터 로드 (예시)
    corpus = nouns_list[i]

    # 단어 빈도수 계산
    word_frequencies = count_word_frequencies(corpus)
    word_frequencies = {key: value for key, value in word_frequencies.items() if value >=50}
    word_frequencies = {key: value for key, value in word_frequencies.items() if len(key) >=2}
    word_frequencies_list.append(word_frequencies)

In [376]:
word_fre_list=[]

In [377]:
for i in range(8):
    word_fre_list.append(sorted(word_frequencies_list[i].items(),reverse=True,key=lambda item: item[1]))
    word_fre_list[i] = dict(word_fre_list[i])

# 2차 정제한 명사,빈도 피클로 저장

In [378]:
len(word_fre_list)

8

In [368]:
import pickle

In [379]:
with open("pickle3_second.pkl","wb") as f:
    pickle.dump(word_fre_list, f)

# 피클 불러오기

In [380]:
with open('pickle1_second.pkl', 'rb') as f:
    data1 = pickle.load(f)

In [381]:
with open('pickle2_second.pkl', 'rb') as f:
    data2= pickle.load(f)

In [382]:
with open('pickle3_second.pkl', 'rb') as f:
    data3 = pickle.load(f)

data2_city = ['paju','pohang','seoguepo','seoul','siheung','jeju','tongyoung']
data1_city = ['mokpo', 'gangreung', 'yeosu','hwasung','buan','bosung','changwon','chungju','gyungju','taean']
data3_city = ['incheon', 'namyangju','daegu','daejeon' ,'yongin' ,'gwangju','ulsan','yangyang']

In [383]:
print(len(data1))
print(len(data2))
print(len(data3))

8
10
8

## 2차 정제한 피클 상위 30개 추출

In [388]:
for j in range(8):
    a = []
    
    for i in data3[j].keys():
        if i in notuse:
            a.append(i)

    for i in a:
        del data3[j][i]

In [389]:
from itertools import islice

for i in range(8):
    data3[i] = dict(islice(data3[i].items(), 30))

In [393]:
data1_city = ['mokpo','paju','pohang','seoguepo','seoul','siheung','jeju','tongyoung']
data2_city = ['gunsan', 'gangreung', 'yeosu','hwasung','buan','bosung','changwon','chungju','gyungju','taean']
data3_city = ['incheon', 'namyangju','daegu','daejeon' ,'yongin' ,'gwangju','ulsan','yangyang']

In [454]:
import pandas as pd
x = pd.DataFrame()
for i in range(len(data1)):
    a = pd.DataFrame(data1[i],index = [data1_city[i]])
    x = pd.concat([a,x],join='outer')

In [455]:
import pandas as pd
x1 = pd.DataFrame()
for i in range(len(data2)):
    a = pd.DataFrame(data2[i],index = [data2_city[i]])
    x1 = pd.concat([a,x1],join='outer')

In [456]:
import pandas as pd
x2 = pd.DataFrame()
for i in range(len(data3)):
    a = pd.DataFrame(data3[i],index = [data3_city[i]])
    x2 = pd.concat([a,x2],join='outer')

In [457]:
df = pd.concat([x,x1],join='outer')
df = pd.concat([df,x2],join='outer')

In [458]:
df

,루지,케이블카,공원,사량,이순신,미륵산,벽화,바다,전망대,수국,...,수종사,두물머리,다산로,소래포구,센트럴,어시장,해산물,해물,대하,남동구
tongyoung,11120.0,11049.0,8905.0,8718.0,8294.0,7070.0,6954.0,5917.0,3238.0,3027.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
jeju,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6558.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
siheung,NaN,NaN,20713.0,NaN,NaN,NaN,NaN,4084.0,3103.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seoul,NaN,NaN,16389.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seoguepo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4672.0,2561.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pohang,NaN,NaN,1381.0,NaN,NaN,NaN,NaN,3178.0,973.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
paju,NaN,NaN,5425.0,NaN,NaN,NaN,NaN,NaN,2319.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mokpo,NaN,4692.0,3129.0,NaN,NaN,NaN,NaN,3762.0,3153.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
taean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8649.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gyungju,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chungju,NaN,NaN,2266.0,NaN,NaN,NaN,2853.0,NaN,4261.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
changwon,NaN,NaN,9837.0,NaN,NaN,NaN,NaN,1949.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bosung,NaN,NaN,2574.0,NaN,NaN,NaN,NaN,3260.0,2576.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
buan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6757.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hwasung,NaN,2969.0,NaN,NaN,NaN,NaN,NaN,4944.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
yeosu,NaN,6774.0,10769.0,NaN,9203.0,NaN,NaN,11078.0,2843.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gangreung,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7691.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gunsan,NaN,NaN,6020.0,NaN,NaN,NaN,NaN,4732.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
yangyang,NaN,2551.0,NaN,NaN,NaN,NaN,NaN,6027.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ulsan,NaN,NaN,10979.0,NaN,NaN,NaN,NaN,8084.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gwangju,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
yongin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
daejeon,NaN,NaN,5582.0,NaN,NaN,NaN,NaN,NaN,1695.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
daegu,NaN,8800.0,1942.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
namyangju,NaN,NaN,2313.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,778.0,629.0,580.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incheon,NaN,NaN,2098.0,NaN,NaN,NaN,NaN,7019.0,NaN,NaN,...,NaN,NaN,NaN,7346.0,5480.0,4892.0,1598.0,1285.0,1264.0,1144.0

In [459]:
df.fillna(0,inplace=True)

In [460]:
print(df.columns)

Index(['루지', '케이블카', '공원', '사량', '이순신', '미륵산', '벽화', '바다', '전망대', '수국',
       ...
       '수종사', '두물머리', '다산로', '소래포구', '센트럴', '어시장', '해산물', '해물', '대하', '남동구'],
      dtype='object', length=421)

# 단어 정규화 (추가 진행)

In [ ]:
# 클러스터링의 정확도를 위해, 어느정도 데이터 별로 연관성이 필요했다.
# 특정 지역명이 포함된 단어 제거.
# 한국관광데이터랩을 참고해, 관광 키워드 별로 묶이는 단어들을 정규화 진행함.

### 사찰

In [461]:
filtered_columns = [col for col in df.columns if '사' in col]

filtered_columns

['사량',
 '행사',
 '보경사',
 '사찰',
 '보광사',
 '역사관',
 '자연사',
 '역사',
 '근대역사관',
 '영사관',
 '불국사',
 '내소사',
 '용주사',
 '신사임당',
 '사진관',
 '국사',
 '사이드',
 '사파리',
 '수종사']

In [462]:

cols_to_change = ['용주사', '내소사', '보경사', '보광사', '수종사','불국사']
df[cols_to_change].sum(axis=1)

df['사찰'] = df['사찰'] +df[cols_to_change].sum(axis=1)

df.drop(['용주사', '내소사', '보경사', '보광사', '수종사','불국사'],axis=1,inplace=True)

### 해수욕장, 해산물

In [463]:
filtered_columns = [col for col in df.columns if '해' in col]

filtered_columns

['해수욕장', '해변', '재해', '협재해수욕장', '해수', '진해', '해양', '해식', '서해', '해산물', '해물']

In [464]:
df.drop(['서해','재해','진해','재해'],axis=1,inplace=True)
df.drop(['해식','해수'],axis=1,inplace=True)

In [465]:
cols_to_change = ['해변', '협재해수욕장']
df[cols_to_change].sum(axis=1)

df['해수욕장'] = df['해수욕장'] +df[cols_to_change].sum(axis=1)

df.drop(['해변', '협재해수욕장'],axis=1,inplace=True)

df['해산물'] = df['해산물'] + df['해물']
df.drop(['해물'],axis=1,inplace=True)

### '구'

In [466]:
filtered_columns = [col for col in df.columns if '구' in col]

filtered_columns

['구좌읍', '구이', '구룡포', '놀이기구', '기구', '야구', '야구장', '구장', '소래포구', '남동구']

In [467]:
cols_to_change = ['구장', '야구']
df[cols_to_change].sum(axis=1)

df['야구장'] = df['야구장'] +df[cols_to_change].sum(axis=1)

df.drop(['구좌읍', '구룡포','남동구','소래포구','구장','야구'],axis=1,inplace=True)

### '도'

In [468]:
filtered_columns = [col for col in df.columns if '도' in col]
filtered_columns

['파도',
 '여의도',
 '오륙도',
 '안면도',
 '우도',
 '변산반도',
 '제부도',
 '부도',
 '오동도',
 '선유도',
 '장자도',
 '고군산군도',
 '유도',
 '옥도면',
 '무녀도',
 '신시도']

In [469]:
cols_to_change = ['제부도', '부도','오동도','변산반도']
df[cols_to_change].sum(axis=1)

df['섬'] =df[cols_to_change].sum(axis=1)

df.drop(['여의도','제부도', '부도','오동도','변산반도'],axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/1649331249.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['섬'] =df[cols_to_change].sum(axis=1)

### '관'

In [470]:
filtered_columns = [col for col in df.columns if '관' in col]
filtered_columns

['박물관', '미술관', '역사관', '근대역사관', '영사관', '본관', '기념관', '사진관', '관람차', '수족관', '직관']

In [471]:
cols_to_change = ['박물관', '미술관', '수족관', '기념관']
df[cols_to_change].sum(axis=1)

df['문화역사체험관'] =df[cols_to_change].sum(axis=1)

df.drop(['직관','박물관', '미술관', '수족관', '기념관'],axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/3220987823.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['문화역사체험관'] =df[cols_to_change].sum(axis=1)

### '원'

In [472]:
filtered_columns = [col for col in df.columns if '원' in col]
filtered_columns

['공원',
 '동물원',
 '수목원',
 '정원',
 '목원',
 '청주동물원',
 '국립공원',
 '초원',
 '응원',
 '응원가',
 '한밭수목원',
 '식물원']

In [473]:
cols_to_change = ['동물원', '수목원', '목원', '한밭수목원', '식물원']
df[cols_to_change].sum(axis=1)

df['동식물원'] =df[cols_to_change].sum(axis=1)

cols_to_change = ['국립공원','정원']
df[cols_to_change].sum(axis=1)

df['공원'] = df['공원'] + df[cols_to_change].sum(axis=1)

df.drop(['응원','응원가','물의','동물원', '수목원', '목원', '한밭수목원', '식물원','국립공원','정원'],axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/3897737011.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['동식물원'] =df[cols_to_change].sum(axis=1)

### '읍' 삭제

In [474]:
filtered_columns = [col for col in df.columns if '읍' in col]
filtered_columns

df.drop(filtered_columns,axis=1,inplace=True)

In [475]:
three_letter_columns = [col for col in df.columns if len(col) == 3]
print(three_letter_columns)

['이순신', '미륵산', '전망대', '지리산', '스카이', '옥녀봉', '리프트', '비자림', '만장굴', '한라산', '웨이브', '거북섬', '물놀이', '놀이터', '신석기', '경복궁', '코엑스', '스토어', '데이트', '전시회', '백화점', '오설록', '일출봉', '서귀포', '한탄강', '하우스', '휘닉스', '내연산', '호미곶', '송라면', '임진각', '헤이리', '나들이', '캠핑장', '곤돌라', '둘레길', '자전거', '유달산', '역사관', '자연사', '노적봉', '오륙도', '승강장', '방공호', '소양강', '영사관', '안면도', '태안군', '몽산포', '리조트', '맛조개', '첨성대', '석굴암', '드라켄', '문화재', '다보탑', '천마총', '청남대', '대통령', '대청댐', '휴게소', '대청호', '물고기', '생태학', '떡갈비', '엑스포', '삼나무', '격포항', '곰소항', '바지락', '전나무', '진서면', '칼국수', '궁평항', '수산물', '전곡항', '동백꽃', '아르떼', '오죽헌', '경포호', '주문진', '경포대', '오징어', '순두부', '먹거리', '닭강정', '선유도', '사진관', '장자도', '비응항', '옥도면', '무녀도', '신시도', '방조제', '체스터', '설악산', '수영장', '관람차', '대왕암', '간절곶', '장생포', '돌고래', '광역시', '산책로', '송정역', '야구장', '경기장', '떡볶이', '민속촌', '백남준', '사이드', '레이크', '골프장', '오월드', '장태산', '신세계', '사파리', '한빛탑', '휴양림', '팔공산', '이월드', '엑스코', '박람회', '정약용', '유적지', '양귀비', '여유당', '한강로', '다산로', '센트럴', '어시장', '해산물']

### '항'

In [476]:
filtered_columns = [col for col in df.columns if '항' in col]
filtered_columns
df['항구'] =df[filtered_columns].sum(axis=1)

df.drop(filtered_columns,axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/1751728782.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['항구'] =df[filtered_columns].sum(axis=1)

### '장'

In [477]:
filtered_columns = [col for col in df.columns if '장' in col]
filtered_columns

['장군',
 '해수욕장',
 '장굴',
 '만장굴',
 '시장',
 '마장',
 '캠핑장',
 '승강장',
 '공장',
 '수산시장',
 '광장',
 '게장',
 '중앙시장',
 '대장',
 '장자도',
 '수영장',
 '장생포',
 '야구장',
 '경기장',
 '골프장',
 '장태산',
 '장미',
 '서문시장',
 '어시장']

In [478]:
df['시장'] =df['시장'] + df[['수산시장','중앙시장','서문시장','어시장']].sum(axis=1)
df.drop(['장군','마장','수산시장','중앙시장','서문시장','어시장'],axis=1,inplace=True)

### '굴'

In [479]:
filtered_columns = [col for col in df.columns if '굴' in col]
filtered_columns

['장굴', '만장굴', '동굴', '석굴암', '굴암']

In [480]:
df[filtered_columns].sum(axis=1)

df['동굴'] = df['동굴'] + df[filtered_columns].sum(axis=1)

df.drop(['장굴','만장굴'],axis=1,inplace=True)

### 면 삭제

In [481]:
filtered_columns = [col for col in df.columns if '면' in col]
filtered_columns

['라면', '송라면', '안면도', '안면', '진서면', '옥도면']

In [482]:
df.drop(filtered_columns,axis=1,inplace=True)

### '스'

In [483]:
filtered_columns = [col for col in df.columns if '스' in col]
filtered_columns

['스카이라인',
 '스카이',
 '스타',
 '코엑스',
 '스토어',
 '하우스',
 '아이스크림',
 '휘닉스',
 '스파',
 '엑스포',
 '크리스마스',
 '체스터',
 '톤스',
 '엑스포로',
 '챔피언스',
 '엑스코',
 '코스모스']

In [484]:
cols_to_change = ['엑스포','엑스포로','엑스코']
df['과학기술체험관'] =df[cols_to_change].sum(axis=1)
df.drop(cols_to_change,axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/2783407305.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['과학기술체험관'] =df[cols_to_change].sum(axis=1)

In [485]:
df.drop(['스타','스토어','하우스','휘닉스','체스터','톤스','챔피언스'],axis=1,inplace=True)

### '해산물'

In [486]:
seafood_list = ["연어","굴","조개","오징어","새우","대구","갈치","문어","전복","가자미","홍합","전어",
                '회',"갑오징어","멸치","참치","해삼","꽃게","우럭",'광어','해삼','멍게','대하','대게','꼬막','수산물']

In [487]:
filtered_columns = [col for col in df.columns if col in seafood_list]
filtered_columns

df['해산물'] = df['해산물'] + df[filtered_columns].sum(axis=1)
df.drop(filtered_columns,axis=1,inplace=True)

### '산'

In [488]:
filtered_columns = [col for col in df.columns if '산' in col]
filtered_columns

['미륵산',
 '등산',
 '산행',
 '지리산',
 '산책',
 '한라산',
 '성산',
 '성산일출봉',
 '연산',
 '내연산',
 '유달산',
 '몽산포',
 '상당산성',
 '산성',
 '성산아트홀',
 '암산',
 '송산',
 '돌산',
 '돌산대교',
 '고군산군도',
 '설악산',
 '산책로',
 '장태산',
 '팔공산',
 '다산',
 '다산로',
 '해산물']

In [489]:
cols_to_change = ['미륵산','등산','산행','지리산','한라산','성산','성산일출봉','연산','내연산','설악산','장태산','팔공산']
df['산'] =df[cols_to_change].sum(axis=1)
df.drop(cols_to_change,axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/4002209057.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['산'] =df[cols_to_change].sum(axis=1)

In [490]:
filtered_columns = [col for col in df.columns if '로' in col]
filtered_columns

df['산책'] =df['산책'] + df[['산책로']].sum(axis=1)
df.drop(filtered_columns,axis=1,inplace=True)

In [491]:
for i in df.columns:
    print(i)

루지
케이블카
공원
사량
이순신
벽화
바다
전망대
수국
풍경
카페
스카이라인
바위
스카이
옥녀봉
자연
횟집
전망
산책
여름
낚시
식당
리프트
언덕
체험
해수욕장
비자림
함덕
절물
자연휴양림
오름
동굴
협재
용암
비자나무
고기
호텔
비자
웨이브
파크
갯골
생태
서핑
거북섬
파도
물놀이
놀이터
시장
갯벌
놀이
유적
신석기
전시
소금
모래
오이
가을
한강
경복궁
코엑스
커피
팝업
예술의전당
공연
예술
라울
음식
텐트
데이트
한복
전시회
전당
뚝섬
벚꽃
백화점
행사
폭포
섭지코지
오설록
주상절리
녹차
일출봉
서귀포
천지
한탄강
조림
천지연폭포
아이스크림
주상
구이
계곡
호미곶
전통
가옥
웨딩
펜션
힐링
사찰
호수
평화
임진각
누리
벽초
헤이리
나들이
캠핑장
곤돌라
진각
둘레길
캠핑
자전거
하늘
돌라
유달산
역사관
자연사
역사
공룡
근대역사관
노적봉
오륙도
승강장
델루
방공호
소양강
화석
영사관
꽃지
아일랜드
리솜
태안군
몽산포
천리
오션
리조트
포수
스파
일몰
맛조개
첨성대
월드
국립
석굴암
신라
월지
황리
대릉
굴암
동궁
유물
놀이기구
드라켄
야경
문화재
정교
다보탑
핑크
천마총
청남대
랜드
상당산성
대통령
대청댐
동물
청주동물원
산성
명암
청댐
청호
드라이브
휴게소
대청호
본관
해양
과학
타워
용지
성산아트홀
보트
물고기
생물
우도
어류
공장
생태학
아트
실내
기구
율포
축제
떡갈비
암산
센터
차밭
솔밭
데크
삼나무
채석
젓갈
백합
바지락
전나무
노을
칼국수
온천
요트
송산
광장
돌산
김밥
버거
낭만
게장
동백꽃
돌산대교
동백
딸기
등대
포차
아르떼
오죽헌
안목
경포호
주문진
경포
경포대
순두부
율곡
초당
먹거리
닭강정
신사임당
물회
선유도
사진관
초원
대장
국사
장자도
고군산군도
유도
철길
무녀도
크리스마스
신시도
방조제
청초
수영장
관람차
튀김
본점
순대
오징어순대
고래
대왕암
간절곶
장생포
돌고래
광역시
모노레일
일출
소망
기아
필드
송정역
타이거즈
야구장
경기장
국밥
치킨
맥주
떡볶이
국수
계란
롯데
투수
영명
호두과자
양갱
식빵
크림
에버랜드
민속촌
베이
캐리비안
백남준
사이드
레이크
골프
골프장
바오
판다
클럽
그린
컨트리클럽
아쿠아리움
오월드
신세계
장미
음악분수
사파리
한빛탑
수조
휴양림
이월드
인터
단풍
갈비
박람회
피자
정약용
다산
유적지
양귀비
실학
코스모스
생가
여유당
강변
두물머리
센트럴
해산물
섬
문화역사체험관
동식물원
항구
과학기술체험관
산

### 음식

In [492]:
cols_to_change = ['칼국수', '게장', '순두부', '먹거리' , '닭강정', '물회' , '떡갈비' , '젓갈' ,
                 '순대','오징어순대','튀김','본점','국밥','치킨','맥주','떡볶이','국수','계란','호두과자',
'양갱','식빵','크림','피자']
df['음식'] =df[cols_to_change].sum(axis=1)
df.drop(cols_to_change,axis=1,inplace=True)

### '삭제'

In [493]:
cols_to_change = ['송산', '이순신', '랜드', '돌산','다산','암산', '돌산' , '안목', '경포', '경포대', '초당' , '율포' ,
                  '센터','경포','전망','비자림','함덕','절물','협재','용암','비자','웨이브',
 '라울','갯골','파도','거북섬','한복','뚝섬','하늘','율포','모래','오설록','서귀포','조림',
'웨딩','평화','임진각','누리','벽초','헤이리','진각','고래','장생포','돌고래','광역시','소망','기아','필드',
'송정역','타이거즈','롯데','투수','영명','베이','백남준','이순신','사이드','레이크',
'바오','음악분수','한빛탑','인터','클럽','월드','그린','수조','다산','실학','여유당','두물머리','센트럴','오션','암산' , '데크' , '사량','정약용' ]
df.drop(cols_to_change,axis=1,inplace=True)

### 바다 액티비티

In [494]:
cols_to_change = ['낚시','생태','서핑']
df['바다액티비티'] =df[cols_to_change].sum(axis=1)
df.drop(cols_to_change,axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/3981685749.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['바다액티비티'] =df[cols_to_change].sum(axis=1)

### 바위

In [495]:
cols_to_change = ['옥녀봉','섭지코지','주상절리','주상','호미곶','대왕암','간절곶']
df['바위'] =df['바위'] +df[cols_to_change].sum(axis=1)
df.drop(cols_to_change,axis=1,inplace=True)

### 강

In [496]:
cols_to_change = ['채석','한탄강',]
df['강'] = df[cols_to_change].sum(axis=1)
df.drop(cols_to_change,axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/1688189402.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['강'] = df[cols_to_change].sum(axis=1)

### 액티비티

In [497]:
cols_to_change = ['루지','리프트','스카이','곤돌라','돌라','관람차','놀이터','놀이','모노레일','에버랜드','놀이기구',
'사파리']
df['액티비티'] = df[cols_to_change].sum(axis=1)
df.drop(cols_to_change,axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/2078287264.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['액티비티'] = df[cols_to_change].sum(axis=1)

### 식물

In [498]:
cols_to_change = ['수국','동백','동백꽃','솔밭','삼나무','전나무','비자나무','장미','양귀비','코스모스']
df['식물'] = df[cols_to_change].sum(axis=1)
df.drop(cols_to_change,axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/3055847574.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['식물'] = df[cols_to_change].sum(axis=1)

### 문화

In [499]:
cols_to_change = ['팝업','공연','축제','전시회','전당','예술의전당','백화점']
df['문화'] = df[cols_to_change].sum(axis=1)
df.drop(cols_to_change,axis=1,inplace=True)

/var/folders/y3/l8bvkgx53cd0nbrk2b450t7m0000gn/T/ipykernel_1030/2248689056.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['문화'] = df[cols_to_change].sum(axis=1)

## 클러스터링

In [500]:
total_sum = df.sum(axis=1)
keyword_ratio = df.apply(lambda x: round(x/total_sum,2),axis=0) # 수치 정규화
keyword_ratio

,케이블카,공원,벽화,바다,전망대,풍경,카페,스카이라인,바위,자연,...,문화역사체험관,동식물원,항구,과학기술체험관,산,바다액티비티,강,액티비티,식물,문화
tongyoung,0.13,0.10,0.08,0.07,0.04,0.03,0.03,0.03,0.04,0.02,...,0.00,0.00,0.00,0.00,0.15,0.01,0.00,0.16,0.04,0.00
jeju,0.00,0.00,0.00,0.09,0.00,0.03,0.07,0.00,0.00,0.03,...,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.03,0.00
siheung,0.00,0.20,0.00,0.04,0.03,0.02,0.04,0.00,0.00,0.00,...,0.08,0.00,0.00,0.00,0.00,0.14,0.00,0.04,0.00,0.00
seoul,0.00,0.18,0.00,0.00,0.00,0.00,0.05,0.00,0.00,0.00,...,0.02,0.02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.17
seoguepo,0.00,0.00,0.00,0.05,0.02,0.03,0.06,0.00,0.19,0.02,...,0.00,0.00,0.00,0.00,0.14,0.00,0.03,0.00,0.00,0.00
pohang,0.00,0.03,0.00,0.07,0.02,0.02,0.05,0.00,0.03,0.02,...,0.00,0.00,0.00,0.00,0.12,0.00,0.00,0.00,0.00,0.00
paju,0.00,0.11,0.00,0.00,0.03,0.03,0.10,0.00,0.00,0.00,...,0.02,0.10,0.00,0.00,0.00,0.00,0.00,0.05,0.00,0.00
mokpo,0.06,0.04,0.00,0.05,0.04,0.03,0.04,0.00,0.03,0.00,...,0.07,0.00,0.01,0.00,0.00,0.00,0.00,0.12,0.00,0.00
taean,0.00,0.00,0.00,0.07,0.00,0.00,0.03,0.00,0.02,0.00,...,0.00,0.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
gyungju,0.00,0.00,0.00,0.00,0.00,0.01,0.04,0.00,0.00,0.00,...,0.10,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00
chungju,0.00,0.03,0.03,0.00,0.05,0.02,0.06,0.00,0.00,0.00,...,0.02,0.07,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.00
changwon,0.00,0.12,0.00,0.02,0.00,0.00,0.02,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.06,0.00,0.04
bosung,0.00,0.03,0.00,0.04,0.03,0.03,0.02,0.00,0.00,0.02,...,0.02,0.00,0.00,0.03,0.00,0.00,0.00,0.00,0.04,0.07
buan,0.00,0.01,0.00,0.08,0.00,0.02,0.03,0.00,0.00,0.00,...,0.00,0.00,0.09,0.00,0.00,0.00,0.13,0.00,0.02,0.00
hwasung,0.04,0.00,0.00,0.07,0.00,0.02,0.06,0.00,0.02,0.00,...,0.00,0.00,0.13,0.00,0.00,0.02,0.00,0.00,0.00,0.00
yeosu,0.06,0.09,0.00,0.09,0.02,0.02,0.05,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.04,0.00
gangreung,0.00,0.00,0.00,0.06,0.00,0.00,0.06,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
gunsan,0.00,0.06,0.00,0.05,0.00,0.03,0.05,0.00,0.02,0.00,...,0.00,0.00,0.03,0.00,0.00,0.03,0.00,0.00,0.00,0.00
yangyang,0.02,0.03,0.00,0.05,0.00,0.00,0.03,0.00,0.02,0.00,...,0.00,0.00,0.00,0.01,0.07,0.00,0.00,0.03,0.00,0.00
ulsan,0.00,0.11,0.00,0.08,0.00,0.02,0.04,0.00,0.22,0.00,...,0.06,0.00,0.00,0.00,0.00,0.08,0.00,0.01,0.00,0.01
gwangju,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
yongin,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.02,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.24,0.00,0.05
daejeon,0.00,0.05,0.00,0.00,0.02,0.00,0.02,0.00,0.00,0.00,...,0.00,0.10,0.00,0.12,0.07,0.00,0.00,0.02,0.02,0.08
daegu,0.09,0.02,0.00,0.00,0.00,0.00,0.06,0.00,0.00,0.00,...,0.00,0.07,0.00,0.07,0.10,0.00,0.00,0.02,0.00,0.02
namyangju,0.00,0.32,0.00,0.00,0.00,0.04,0.03,0.00,0.00,0.02,...,0.05,0.00,0.00,0.00,0.00,0.04,0.00,0.00,0.10,0.00
incheon,0.00,0.03,0.00,0.11,0.00,0.00,0.06,0.00,0.02,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [501]:
keyword_ratio.sum(axis=1) # 정규화가 잘 됐는지 확인

tongyoung    0.99
jeju         0.99
siheung      1.03
seoul        0.99
seoguepo     1.00
pohang       0.97
paju         0.99
mokpo        1.02
taean        1.01
gyungju      0.97
chungju      1.02
changwon     0.99
bosung       1.01
buan         1.01
hwasung      1.01
yeosu        0.99
gangreung    1.01
gunsan       1.04
yangyang     0.98
ulsan        1.00
gwangju      1.00
yongin       1.01
daejeon      1.00
daegu        1.01
namyangju    0.99
incheon      1.00
dtype: float64

In [502]:
keyword_ratio.fillna(0,inplace=True)

In [537]:
# 군집 개수 설정
# 군집 개수는 3~ 15 중 가장 군집 별 특성이 설명 가능하고, 수치가 높았음.
num = 9

In [538]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters = num, random_state=42)
km.fit(keyword_ratio)

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

KMeans(n_clusters=9, random_state=42)

In [539]:
import numpy as np
centers = pd.DataFrame(np.round(km.cluster_centers_, num), columns = km.feature_names_in_)
centers.index.name = "cluster"
centers

,케이블카,공원,벽화,바다,전망대,풍경,카페,스카이라인,바위,자연,...,문화역사체험관,동식물원,항구,과학기술체험관,산,바다액티비티,강,액티비티,식물,문화
cluster,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0.000000,0.0000,0.000000,0.000000,0.010,0.040000,0.000,0.000000,0.000000,...,0.100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030000,0.000000,0.000000
1,0.037500,0.047500,0.0075,0.022500,0.022500,0.010,0.047500,0.000,0.000000,0.000000,...,0.005,0.060000,0.000000,0.047500,0.042500,0.000000,0.000000,0.020000,0.015000,0.025000
2,0.000000,0.000000,0.0000,0.000000,0.000000,0.000,0.030000,0.000,0.000000,0.000000,...,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.233333,0.0000,0.013333,0.010000,0.020,0.040000,0.000,0.000000,0.006667,...,0.050,0.006667,0.000000,0.000000,0.000000,0.060000,0.000000,0.013333,0.033333,0.056667
4,0.006667,0.020000,0.0000,0.073333,0.000000,0.000,0.050000,0.000,0.013333,0.000000,...,0.000,0.000000,0.000000,0.003333,0.023333,0.000000,0.000000,0.010000,0.000000,0.000000
5,0.038000,0.074000,0.0160,0.028000,0.022000,0.018,0.044000,0.006,0.014000,0.008000,...,0.018,0.020000,0.002000,-0.000000,0.030000,0.002000,-0.000000,0.126000,0.008000,0.018000
6,0.000000,0.030000,0.0000,0.040000,0.030000,0.030,0.020000,0.000,0.000000,0.020000,...,0.020,0.000000,0.000000,0.030000,0.000000,0.000000,0.000000,0.000000,0.040000,0.070000
7,0.006667,0.016667,0.0000,0.071667,0.003333,0.020,0.048333,0.000,0.015000,0.008333,...,0.000,0.010000,0.041667,0.000000,0.025000,0.008333,0.021667,0.000000,0.008333,0.000000
8,0.000000,0.055000,0.0000,0.065000,0.010000,0.025,0.050000,0.000,0.205000,0.010000,...,0.030,0.000000,0.000000,0.000000,0.070000,0.040000,0.015000,0.005000,0.000000,0.005000

In [540]:

for i in range(num):
    print(pd.DataFrame(centers.iloc[i]).sort_values(by = i, ascending = False)[:5])
    print("-"*30)

            0
사찰       0.11
문화역사체험관  0.10
첨성대      0.09
동굴       0.08
석굴암      0.06
------------------------------
              1
동식물원     0.0600
과학기술체험관  0.0475
카페       0.0475
공원       0.0475
산        0.0425
------------------------------
        2
음식   0.45
야구장  0.29
시장   0.14
경기장  0.09
카페   0.03
------------------------------
                3
공원       0.233333
바다액티비티   0.060000
문화       0.056667
문화역사체험관  0.050000
체험       0.046667
------------------------------
             4
음식    0.130000
해수욕장  0.113333
해산물   0.096667
시장    0.093333
바다    0.073333
------------------------------
          5
액티비티  0.126
공원    0.074
체험    0.060
카페    0.044
호수    0.044
------------------------------
         6
녹차    0.31
문화    0.07
해수욕장  0.07
음식    0.06
체험    0.05
------------------------------
             7
해수욕장  0.130000
바다    0.071667
카페    0.048333
사찰    0.046667
동굴    0.043333
------------------------------
          8
바위    0.205
해수욕장  0.080
산     0.070
바다    0.065
공원    0.055
------------------------------

In [516]:
# 0: 경주: 역사 체험
# 1: 청주 여수 대전 대구 : 동물, 수목원, 과학 체험관
# 2: 광주 : 스포츠 직관, 맛집
# 3: 시흥 서울 남양주 : 공원, 예술 문화 생활 (전시회, 예술 등)
# 4: 강릉 양양 인천 : 바다 관광 
# 5: 통영 파주 목포 창원 용인 : 내륙 액티비티 및 공원, 생태 체험 등
# 6: 보성 : 지역 특산물, 녹차밭 등
# 7: 제주 포항 태안 부안 화성 군산 : 바다 힐링, 지역 문화 체험
# 8: 서귀포 울산 : 자연 경관, 힐링

In [541]:
keyword_ratio['cluster'] = km.predict(keyword_ratio)

In [542]:
keyword_ratio[keyword_ratio['cluster'] == 0 ].index

Index(['gyungju'], dtype='object')

In [543]:
keyword_ratio[keyword_ratio['cluster'] == 1 ].index

Index(['chungju', 'yeosu', 'daejeon', 'daegu'], dtype='object')

In [544]:
keyword_ratio[keyword_ratio['cluster'] == 2 ].index

Index(['gwangju'], dtype='object')

In [545]:
keyword_ratio[keyword_ratio['cluster'] == 3 ].index

Index(['siheung', 'seoul', 'namyangju'], dtype='object')

In [546]:
keyword_ratio[keyword_ratio['cluster'] == 4 ].index

Index(['gangreung', 'yangyang', 'incheon'], dtype='object')

In [547]:
keyword_ratio[keyword_ratio['cluster'] == 5 ].index

Index(['tongyoung', 'paju', 'mokpo', 'changwon', 'yongin'], dtype='object')

In [549]:
keyword_ratio[keyword_ratio['cluster'] == 6 ].index

Index(['bosung'], dtype='object')

In [550]:
keyword_ratio[keyword_ratio['cluster'] == 7 ].index

Index(['jeju', 'pohang', 'taean', 'buan', 'hwasung', 'gunsan'], dtype='object')

In [551]:
keyword_ratio[keyword_ratio['cluster'] == 8 ].index

Index(['seoguepo', 'ulsan'], dtype='object')